openapi: 3.0.2
servers: []
info:
  version: "draft.3"
  title: GA4GH Beacon Variant Annotation Default Schema
  description: >-
    Schema for variant annotations to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    GenomicFeature:
      description: |
        Genomic feature(s) affected by the variant
      type: object
      properties:
        class:
          description: |
            Class of genomic region affected by the variant
          type: string
          enum:
            - gene 
            - protein coding transcript 
            - untranslated region 
            - non-coding transcript
          example: "gene"
        featureID:
          description: |
            ID /accession/name of genomic region affected by the variant, matching class in `class`
          type: string
          example:
            - 'TP53'
            - 'GeneID:43740578'
    VariantAnnotation:
      description: TBD # TBD
      type: object
      properties:
        variantId:
          description: |
            Reference to Variant ID.
          type: string
        variantAlternativeId:
          description: |
            List of cross-referencing ID(s) (CURIE(s)) for the variant in the original
            databases or variant-level (aggregated) databases for previously described
            variants (e.g. clinVarId, ClinGen, COSMIC), e.g. "VCV000055583.1", "CA003602".
          type: array
          items:
            type: string
          example: 
            - 'rs80356868'
            - 'CA003602'
            - 'VCV000055583.1'
        genomicHGVSId:
          description: |
            HGVSId descriptor at genomic level, referred to genome assembly 
            defined in Variant Identification.
          type: string
          example: 'NC_000011.9:g.134086816T>C'
        transcriptHGVSId:
          description: |
            List of HGVSId descriptor(s) at transcript level.
          type: array
          items:
            type: string
          example: 
            - 'NC 000023.10(NM004006.2):c.357+1G'
        proteinHGVSIds:
          description: |
            List of HGVSId descriptor(s) at protein level (for protein-altering 
            variants).
          type: array
          items:
            type: string
          example: 
            - 'NP_009225.1:p.Glu1817Ter'
            - 'LRG 199p1:p.Val25Gly (preferred)'
        genomicRegions:
          description: |
            List of classification(s) of the variant according to the genomic 
            region affected (all that apply, relative to each feature affected). Value from Ensembl
            Glossary (ENSGLOSS)
          type: array
          items:
            type: string
          example: 
            - 'intergenic'
            - '5UTR'
            - '3UTR'
            - 'coding'
        genomicFeatures:
          description: |
            List of Genomic feature(s) affected by the variant.
          type: array
          items:
            $ref: '#/components/schemas/GenomicFeature'
        annotationToolVersion:
          description: |
            Tool used for annotation and prediction of variant effects 
          type: string
          example: 'SnpEffVersion=4.3t (build 2017-11-24 1018)'
        molecularEffect:
          description: |
            List of predicted effect at nucleotide level
          type: array
          items:
            type: string
          example:
            - 'STOP_GAINED'
        molecularConsequence:
          description: |
            List of Predicted effect at protein level for protein affecting variants (Ontology label)
          type: array
          items:
            type: string
          example: 
            - 'nonsense'
            - 'missense'       
        aminoacidChange:
          description: |
            Lisf of change(s) at aminoacid level for protein affecting variants 
          type: array
          items:
            type: string
          example:
            - 'V304*'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue