openapi: 3.0.2
servers: []
info:
  version: "draft.3.1"
  title: GA4GH Beacon Variant in Sample Default Schema
  description: >-
    Schema for variant in sample to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    ClinicalRelevance: 
      description: |
        List of observed effect(s) of variant on disease.
      type: object
      required:
        - diseaseId
      properties:
        diseaseId:
          allOf:
            - description: |
                Descriptor of disease associated. Value from ICD10 disease codes 
                or ontology terms from disease ontologies such as HPO, OMIM, 
                Orphanet, MONDO, e.g. lactose intolerance (HP:0004789).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'HP:0004789'
                label: 'lactose intolerance'
        clinicalEffect:
          allOf:
            - description: |
                Clinical effect classification.  Value from Sequence types and 
                features ontology (SO)  variant  phenotype  (SO:0001769),  e.g. 
                disease causing variant (SO:0001772).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'SO:0001772'
                label: 'disease causing variant'
        evidenceType:
          allOf:
            - description: |
                Ontology value for type of evidence supporting variant-disease 
                association from the Evidence & Conclusion Ontology (ECO), e.g. 
                experimental evidence.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'ECO:0000006'
                label: 'experimental evidence'
    PhenotypicEffect:
      description: |
        List of observed effect(s) of variant on phenotype.
      type: object
      required:
        - phenotypeId
      properties:
        phenotypeId:
          allOf:
            - description: |
                Descriptor of phenotype found associated to variant in the present 
                study. Value from Human Phenotype Ontology (HPO).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        phenotypeEffect:
          allOf:
            - description: |
                Phenotypic effect classification determined in the present 
                study. Value from Sequence types  and  features  ontology  (SO) 
                variant phenotype (SO:0001769), e.g. quantitative variant
                (SO:0001774).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'SO:0001774'
                label: 'quantitative variant'
        evidenceType:
          allOf:
            - description: |
                Type of evidence supporting variant-phenotype association from 
                the Evidence & Conclusion Ontology (ECO), e.g. experimental 
                evidence.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'ECO:0000006'
                label: 'experimental evidence'
    VariantInSample:
      description: |
        TBD
      type: object
      required:
        - variantId
        - biosampleId
      properties:
        variantId:
          description: |
            Reference to variant ID.
          type: string
        analysisId:
          description: |
            Reference to analysis ID.
          type: string
          example: 'SRR10903401'
        biosampleId:
          description: |
            Reference to biosample ID.
          type: string
        variantFrequency:
          description: |
            Variant/allele frequency in biosample.
          type: number
          minimum: 0
          example: 1
        zigosity:
          allOf:
            - description: |
                Zigosity in which variant is present in the sample. Value from 
                the  Zigosity Ontology (GENO:0000133), e.g. heterozygous 
                (GENO:0000135).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'GENO:0000135'
                label: 'heterozygous'
        alleleOrigin:
          allOf:
            - description: |
                Allele origin of variant in sample. Value from the Variant 
                Origin (SO:0001762), e.g. somatic variant, germline variant, 
                de novo variant.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'SO:0001778'
                label: 'germline variant'
        clinicalRelevances:
          type: array
          items:
            $ref: '#/components/schemas/ClinicalRelevance'
        phenotypicEffects:
          type: array
          items:
            $ref: '#/components/schemas/PhenotypicEffect'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue