openapi: 3.0.2
servers: []
info:
  version: "draft.3.1"
  title: GA4GH Beacon Variant Interpretation Default Schema
  description: >-
    Schema for variant interpretations to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    ClinicalRelevance: 
      description: |
        Annotated effect(s) of variant on disease.
      type: object
      required:
        - diseaseId
      properties:
        diseaseId:
          allOf:
            - description: |
                Value from ICD10 disease codes or ontology terms from disease 
                ontologies such as HPO, OMIM, Orphanet, MONDO. e.g. lactose 
                intolerance (ICD10CM:E73).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'ICD10CM:E73'
                label: 'lactose intolerance'
        clinicalEffect:
          allOf:
            - description: |
                Clinical effect classification. Value from Sequence types and 
                features ontology (SO) variant phenotype (SO:0001769), 
                e.g. disease associated variant (SO:0001771).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'SO:0001771'
                label: 'disease associated variant'
        alleleOrigin:
          allOf:
            - description: |
                Annotation(s)  on  allele origins in which  the  variant  has  
                been  in  association  to  condition.  Value(s)  from  Sequence 
                types and features ontology (SO) variant origin (SO:0001762) 
                ontology, e.g. somatic variant (SO:0001777), germline 
                variant (SO:0001778), de novo variant (SO:0001781).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'SO:0001777'
                label: 'somatic variant'
        references:
          description: |
            List of publication identifier(s) Reference(s) to publication(s) 
            describing association, as PMID(s), e.g. PMID:19793655.
          type: array
          items:
            type: string
          example: 
            - 'PMID:19793655”'
    PhenotypicEffect:
      description: |
        List of annotated effect(s) of variant on any phenotypic feature other 
        than a disease.
      type: object
      required:
        - phenotypeId
      properties:
        phenotypeId:
          allOf:
            - description: |
                Descriptor of phenotype found associated. Value from Human 
                Phenotype Ontology (HPO).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        phenotypeEffect:
          allOf:
            - description: |
                Phenotypic effect classification. Value from Sequence types and 
                features ontology (SO) variant phenotype (SO:0001769), e.g. 
                benign variant (SO:0001770).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'SO:0001770'
                label: 'benign variant'
        alleleOrigin:
          allOf:
            -  description: |
                Annotation(s)  on  allele origins in which the variant has been 
                found in  association  to  phenotype.  Value(s)  from  Sequence 
                types and features ontology (SO) variant origin (SO:0001762) 
                ontology, e.g. somatic variant (SO:0001777), germline 
                variant (SO:0001778), de novo variant (SO:0001781).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'SO:0001777'
                label: 'somatic variant'
        references:
          description: |
            Reference(s) to publication(s) describing association, as PMID(s), 
            e.g. “PMID:17024373”.
          type: array
          items:
            type: string
          example: 
            - 'PMID:17024373'
    VariantInterpretation:
      description: |
        TBD
      type: object
      required:
        - variantId
        - datasetId
      properties:
        variantId:
          description: |
            Reference to Variant ID.
          type: string
        datasetId:
          description: |
            Reference to dataset ID source of variant interpretation.
          type: string
        clinicalRelevances:
          type: array
          items:
            $ref: '#/components/schemas/ClinicalRelevance'
        phenotypicEffects:
          type: array
          items:
            $ref: '#/components/schemas/PhenotypicEffect'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValu