openapi: 3.0.2
servers: []
info:
  version: "draft.3"
  title: GA4GH Beacon Dataset Default Schema
  description: >-
    Schema for datasets to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    DatasetDetail:
      description: |
        A dataset is a collection of entities that share a common characteristic, e.g. collected for the same project, having a similar age or being the controls of an study.
      type: object
      properties:
        datasetId:
          description: |
            Dataset reference ID (unique internal ID)
          type: string
        datasetName:
          description: |
            Dataset name. Adding a reference to the dataset source is recommended.
          type: string
          example:  
            - 'DECIPHER'
            - 'DisGeNET'
        datasetype:
          description: |
            Dataset type: variant-level (aggregated) or case-level
          type: string
          enum:
            - variant-level
            - case-level
          example:
            - 'variant-level (aggregated)'
            - 'case-level'
