openapi: 3.0.2
servers: []
info:
  version: "draft.3.1"
  title: GA4GH Beacon Individual Default Schema
  description: |
    Schema for individuals to be used as default by the Beacon.
    
    This object contains info related to the individual from where the variants 
    are found in a study. It includes taxon id and any other relevant 
    information about it, including maybe links or id of genome assemblies and 
    ref seqs associated to this species that are available in the Beacon and 
    that are used for variant identification (location).
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    Disease:
      description: |
        List of disease(s) been diagnosed to the individual, defined by 
        disease ICD10 code, optionally other disease ontology ID(s), age of 
        onset, stage and the presence of family history.
      type: object
      required:
        - diseaseId
      properties:
        diseaseId:
          allOf:
            - description: |
                Disease identifier. Value from ICD10 disease codes or ontology 
                terms from disease ontologies such as HPO, OMIM, Orphanet, 
                MONDO, e.g. lactose intolerance (HP:0004789, ICD10CM:E73).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'HP:0004789'
                label: lactose intolerance
        dateOfOnset:
          description: |
            Date of onset/diagnosis of disease, in ISO8601 date format.
          type: string
          format: date
          example: '1987-10-28'
        onsetType:
          allOf:
            - description: |
                Value from HPO Onset ontology (HP:0003674), e.g. congenital 
                onset (HP:0003577), adult onset (HP:0003581).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: HP:0003581
                label: adult onset
        ageOfOnset:
          allOf:
            - description: |
                Individual's age at onset/diagnosis of disease.
            - $ref: 'common.yaml#/components/schemas/Age'
        stage:
          allOf:
            - description: |
                Value from Ontology for General Medical Science or Disease Stage 
                Qualifier ontology (NCIT:C28108), e.g. acute onset 
                (OGMS:0000119).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'OGMS:0000119'
                label: 'acute onset'
        levelSeverity:
          allOf:
            - description: |
                Level/severity when and as applicable to disease course. 
                Value from Human Phenotype Ontology (HPO) Severity ontology 
                (HP:0012824), e.g. “mild” (HP:0012825)
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'HP:0012825'
                label: 'mild'
        familyHistory:
          description: |
            Boolean indicating determined or self-reported presence of family 
            history of the disease.
          type: boolean
          example: True
    Treatment:
      description: |
        List of treatment(s) or medication(s) been prescribed/administered to 
        individual, defined by treatment ID, date and age of onset, dose, 
        schedule and duration.
      type: object
      required:
        - treatmentId
      properties:
        treatmentId:
          allOf:
            - description: |
                Treatment ID. Value from NCIT Drug, Food, Chemical or Biomedical 
                Material.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        treatmentRoute:
          allOf:
            - description: |
                Route of treatment. Value from NCIT Route of Administration 
                ontology.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        treatmentStartDate:
          description: |
            Date of the beginning of treatment.
          type: string
          example: 'P3Y6M4DT12H30M5S'
        ageAtTreatment:
          allOf:
            - description: |
                Individual's age at the beginning of treatment.
            - $ref: 'common.yaml#/components/schemas/Age'
        treatmentDose:
          description: |
            Treatment dose.
          type: object
          properties:
            doseValue:
              description: |
                Quantity value of Dose.
              type: number
            doseUnits:
              allOf:
                - description: |
                    Treatment dose units. Value from Units of measurement 
                    Ontology (UO).
                - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        schedule:
          allOf:
            - description: |
                Treatment schedule. Value from NCIT Schedule Frequency ontology, 
                e.g weekly (NCIT:C67069).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'NCIT:C67069'
                label: 'weekly'
        duration:
          description: |
            Treatment duration in ISO8601 duration format 
            `P[n]Y[n]M[n]DT[n]H[n]M[n]S`.
          type: string
          example: 'P32Y6M1D'
    Intervention:
      description: |
         Intervention(s) been practiced on Individual, defined by intervention 
         ID, date and age of onset, dose, schedule and duration.
      type: object
      required:
        - interventionId
      properties:
        interventionId:
          allOf:
            - description: |
                Intervention ID. Value from Medical Action Ontology or code from 
                OPCS Classifications of Interventions and Procedures.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        modifier:
          description: Modifier of the intervention. Value from TBD.
          type: string
        interventionDate:
          description: |
            Date of intervention in ISO8601 date format.
          type: string
          example: '2020-05-03'
        ageAtIntervention:
          allOf:
            - description: |
                Individual’s age at the date of intervention.
            - $ref: 'common.yaml#/components/schemas/Age'
    Pedigree:
      description: |
        Pedigree(s) to which the Individual belongs.
      type: object
      required:
        - pedigreeId
      properties:
        pedigreeId:
          description: |
            Reference to pedigree ID.
          type: string
          example: 'Pedigree1001'
        pedigreeDisease:
          allOf:
            - description: |
                Disease ID. Value from ICD10 disease codes or ontology terms 
                from disease ontologies such as HPO, OMIM, Orphanet, MONDO, e.g. 
                lactose intolerance (HP:0004789).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'HP:0004789'
                label: lactose intolerance
        pedigreeRole:
          allOf:
            - description: |
                Pedigree role, defined as relationship to proband. Value from 
                Family member ontology (NCIT:C41256), e.g. proband (NCIT:C64435), 
                identical twin (NCIT:C73429), mother (NCIT:C25189).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'NCIT:C25189'
                label: mother
        affectedStatus:
          description: |
            Affected status of Individual in disease of pedigree: "affected" or 
            "unaffected".
          type: string
          enum:
            - affected
            - unaffected
        numSubjects:
          description: Number of subjects in pedigree.
          type: integer
          example: 10
    PhenotypicFeature:
      description: |
        List of phenotypic feature(s) observed in the individual, 
        defined by phenotype, age of onset and level/ severity. 
      type: object
      required:
        - phenotypeId
      properties:
        phenotypeId:
          allOf:
            - description: |
                Phenotypic feature observed. Value from Human Phenotype Ontology 
                (HPO).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        dateOfOnset:
          description: |
            Date of onset/observation of phenotype, in ISO8601 date format.
          type: string
          format: date
          example: '2010-07-10'
        onsetType:
          allOf:
            - description: |
                Onset type. Value from HPO Onset ontology (HP:0003674), 
                e.g. "congenital onset" (HP:0003577), "adult onset" (HP:0003581).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'HP:0003577'
                label: 'congenital onset'
        ageAtOnset:
          allOf:
            - description: |
                Individual's age at onset/observation of phenotype.
            - $ref: 'common.yaml#/components/schemas/Age'
        levelSeverity:
          allOf:
            - description: |
                Level/severity when and as applicable to phenotype observed. 
                Value from Human Phenotype Ontology (HPO) Severity ontology 
                (HP:0012824), e.g. “severe” (HP:0012828)
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'HP:0012828'
                label: 'severe'
    Measure:
      description: |
        Measures(s) been taken from Individual, defined by measure ID, date 
        and/or age at measure ment, unit and value.
      type: object
      required:
        - measureId
      properties:
        measureId:
          allOf:
            - description: |
                Measure ID. Value from Clinical Measurement ontology (CMO).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        measureQuantity:
          description: |
            TBD
          type: object
          properties:
            measureValue:
              description: |
                 Quantity value of measurement.
              type: number
            measureUnit:
              allOf:
                - description: |
                    Measure units.
                - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        modifier:
          description: Modifier of the measurement. Value from TBD.
          type: string
        measureDate:
          description: Date of measurement, ISO8601 date format.
          type: string
          format: date
        ageAtMeasure:
          allOf:
            - description: |
                Individual's age at the date of measurement.
            - $ref: 'common.yaml#/components/schemas/Age'
    Exposure:
      description: |
        Exposures(s) occurred to or practiced (lifestyle, behavioural exposures) 
        by Individual, defined by exposureID, date and age of onset, dose, 
        schedule and duration.
      type: object
      required:
        - exposureId
      properties:
        exposureId:
          allOf:
            - description: |
                Exposure ID. Value from Environment Exposure Ontology.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
        exposureDose:
          description: |
            Exposure dose.
          type: object
          properties:
              exposureValue:
                description: |
                  Quantity value of exposure.
                type: number
              exposureUnit:
                allOf:
                  - description: |
                      Exposure units
                  - $ref: 'common.yaml#/components/schemas/OntologyTerm'   
        modifier:
          description: |
            Modifier of the exposure. Value from TBD.
          type: string
        exposureDate:
          description: |
            Date of the exposure, in ISO8601 date format.
          type: string
          format: date
          example: '2020-03-17'
        ageAtExposure:
          allOf:
            - description: |
                Individual's age at the date of exposure.
            - $ref: 'common.yaml#/components/schemas/Age'
        duration:
          description: |
            Exposure duration in ISO8601 duration format 
            `P[n]Y[n]M[n]DT[n]H[n]M[n]S`.
          type: string
          example: 'P32Y6M1D'
    Individual:
      description: |
        TBD
      type: object
      required:
        - individualId
      properties:
        individualId:
          description: |
            Individual identifier (external accession or internal ID).
          type: string
          example: P0001
        datasetId:
          description: Reference to dataset ID.
          type: string
        taxonId:
          description: |
            Taxon ID of Individual.
          type: string
          example: '9606'
        sex:
          allOf:
            - description: |
                Sex of the individual.
                Value from NCIT General Qualifier (NCIT:C27993) ontology: 
                UNKNOWN (not assessed or not available) (NCIT:C17998), FEMALE 
                (NCIT:C46113), MALE, (NCIT:C46112) or OTHER SEX (NCIT:C45908).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: NCIT:C17998
                label: UNKNOWN
        ethnicity:
          allOf:
            - description: |
                Ethnic background of the individual. Value from NCIT Race 
                ontology (NCIT:C17049), e.g. NCIT:C126531 (Latin American).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'NCIT:C126531'
                label: Latin American
        geographicOrigin:
          allOf:
            - description: |
                Individual's country or region of origin (birthplace or 
                residence place regardless of ethnic origin). Value from GAZ 
                Geographic Location ontology (GAZ:00000448), e.g. GAZ:00002459 
                (United States of America).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'GAZ:00002459'
                label: United States of America
        diseases:
          type: array
          items:
            $ref: '#/components/schemas/Disease'
        pedigrees:
          type: array
          items:
            $ref: '#/components/schemas/Pedigree'
        phenotypicFeatures:
          type: array
          items:
            $ref: '#/components/schemas/PhenotypicFeature'
        treatments:
          type: array
          items:
            $ref: '#/components/schemas/Treatment'
        interventions:
          type: array
          items:
            $ref: '#/components/schemas/Intervention'
        measures:
          type: array
          items:
            $ref: '#/components/schemas/Measure'
        exposures:
          type: array
          items:
            $ref: '#/components/schemas/Exposure'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3