openapi: 3.0.2
servers: []
info:
  version: "0.1"
  title: GA4GH Beacon Variant Default Schema
  description: >-
    Schema for variants to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    'Beacon Project'
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    Chromosome:
      description: |
        Reference name (chromosome). Accepting values 1-22, X, Y, MT.
      type: string
      enum:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
        - '10'
        - '11'
        - '12'
        - '13'
        - '14'
        - '15'
        - '16'
        - '17'
        - '18'
        - '19'
        - '20'
        - '21'
        - '22'
        - 'X'
        - 'Y'
        - 'MT'
    VariantDetails:
      description: |
        Description of the variant.
      type: object
      properties:
        variantId:
          description: |
            ID referencing the variant in beacon (internal ID)
          type: string
        refseqId:
          description: |
            Reference sequence Refseq ID and version for genomic contiguous in
            which variant query coordinates are given, e.g ”NC 000009” for human chromosome 9. 
            Alternatively, names, synonymous or aliases are accepted eg. ”Chr9” when `assemblyId` is given. 
            For organism with single scaffold the full length reference sequence Refseq IDs can be given here as
            an alternative to the assembly Id and version in `assemblyId`, e.g ”NC 045512.2” for SARS-CoV2
            full-length genome reference sequence.
          type: string
          example: NC 000009
        ref:
          description: |
            Reference bases for this variant (starting from `start`).
          type: string
          pattern: '^([ACGTN]+)$'
        alt:
          description: |
            The bases that appear instead of the reference bases.
          type: string
          pattern: '^([ACGTN]+)$'
        variantType:
          description: |
            Ontology value from Sequence Ontology describing the type of 
            variant, e.g. SNV (SO:0001483), structural variant(SO:0001537).
          type: string
          example: SO:0001483
        start:
          description: |
            Start position of the variant in 0-based (interbase) coordinates.
          type: integer
          format: int64
          minimum: 0
        end:
          description: |
            End position of the variant in 0-based (interbase) coordinates.
          type: integer
          format: int64
          minimum: 1
        assemblyId:
          description: |
            Genomic assembly accession and version as RefSqeq assembly accessions (e.g ”GCG 000001405.39”).
            Alternatively, an assembly name or synonym such as UCSC Genome Browser assembly (e.g ”hg38”) or 
            Genome Reference consortium Human (e.g GRCh38.p13”) names can be given as long 
            as they are accompanied with their versions.
          type: string
          example: GRCh38
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3
