openapi: 3.0.2
servers: []
info:
  version: "draft.3"
  title: GA4GH Beacon Individual Default Schema
  description: >-
    Schema for individuals to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    This object contains info related to the individual from where the variants are found in a study. 
    It includes taxon id and any other relevant information about it, including maybe links or id 
    of genome assemblies and ref seqs associated to this species that are available in the Beacon 
    and that are used for variant identification (location)
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    LevelSeverity:
      description: |
        Level/severity ontology when and as applicable to phenotype observed. Value from TBD, e.g ”mild”.
      type: string
      enum: 
        - #TBD # Source TBD
      example: 'severe'
    DateOfOnset:
      description: |
        Date of onset/observation of phenotype, in (ISO8601 duration format).
      type: string
      example: 'P3Y6M4DT12H30M5S' #TBD to be confirmed
    Disease:
      description: |
        Lisf of disease(s) been diagnosed to the individual, defined by diseaseID, age of onset, 
        stage, level of severity, outcome and the presence of family history.
      type: object
      properties:
        diseaseId:
          description: |
            Disease identifier. Value from ICD10 disease codes or ontology terms 
            from disease ontologies such as HPO, OMIM, Orphanet, MONDO, e.g. 
            lactose intolerance (HP:0004789, ICD10CM:E73).
          type: string
          example:
            - 'HP:0004789'
            - 'ICD10CM:E73'
        ageOfOnset:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
        stage:
          description: |
            Ontology value from Ontology for General Medical Science or Disease 
            Stage Qualifier ontology (NCIT:C28108), e.g. acute onset (OGMS:0000119).
          type: string
          example: 'OGMS:0000119'
        levelSeverity:
          $ref: '#/components/schemas/LevelSeverity'
        outcome:
          description: |
             Outcome of passed acute diseases. Value from TBD, eg. ”fatal”.
          type: string
          enum:
            - TBD #TBD
          example: 'fatal'
        familyHistory:
          description: |
            Boolean indicating determined or self-reported presence of family 
            history of the disease.
          type: boolean
          example: True
    Treatments:
      description: |
        List of treatment(s) been prescribed/administered to individual, defined by treatment ID), date and age of onset, dose, schedule and duration.
      type: object
      properties:
        treatmentId:
          description: |
            Treatment ID. Value from TBD.
          type: string
          example: #TBD
        treatmentRoute:
          description: Route of treatment. Value from NCIT Route of Administration ontology.
          type: string
        dateAtOnset:
          $ref: '#/components/schemas/DateOfOnset'
        ageAtOnset:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
        dose:
          description: |
            Treatment dose
          type: integer
          example: #TBD
        units:
          description: |
            Treatment dose units
          type: string
          example: #TBD
        schedule:
          description: |
            Treatment dose units
          type: string
          enum:
            - #TBD
          example: 'weekly'
        duration:
          description: |
            Treatment duration in ISO8601 duration format
          type: string
          example: 'P32Y6M1D'
    Interventions:
      description: |
        List of intervention(s) been practiced on subject, 
        defined by treatment ID, date and age of onset, dose, 
        schedule and duration.
      type: object
      properties:
        interventionId:
          description: |
            Intervention ID. Value from Medical Action Ontology.
          type: string
          example: #TDB
        date:
          description: |
            Date of intervention in ISO8601 duration format
          type: string
          example: 'P3Y6M4DT12H30M5S' #TBD to be confirmed
        modifier:
          description: Modifier of the intervention. Value from TBD.
          type: string
        ageAtIntervention:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
    Pedigree:
      description: |
        Pedigree studie(s) in which the individual is part of.
      type: object
      properties:
        pedigreeID:
          description: |
            Pedigree identifier.
          type: string
          example: 'Pedigree1001'
        pedigreeDisease:
          description: |
            (disease code/ontology term object) Disease ID. Value from ICD10 disease
            codes or ontology terms from disease ontologies such as HPO, OMIM, Orphanet, MONDO,
            e.g. “lactose intolerance” (HP:0004789)
          type: string
          example: "HP:0004789"
        pedigreeRole:
          description: |
            Pedigree role, defined as relation- ship to proband. Value from Family
            member ontology (NCIT:C41256), e.g. “proband” (NCIT:C64435),
            "identical twin" (NCIT:C73429), "mother" (NCIT:C25189).
          type: string
          example: 'ERO:0002041'
        affectedStatus:
          description: |
            Affected status of Individual in disease of pedigree: “affected” or “unaffected”.
          type: string
          enum:
            - affected
            - unaffected
        numSubjects:
          description: Number of subjects in pedigree.
          type: integer
          example: 10
    PhenotypicFeatures:
      description: |
        List of phenotypic feature(s) observed in the individual, 
        defined by phenotype, age of onset and level/ severity. 
      type: object
      properties:
        phenotypeId:
          description: |
            Phenotypic feature observed. 
            Value from Human Phenotype Ontology (HPO).
          type: string
        dateOfOnset:
          description: |
            Date of onset/observation of phenotype, in (ISO8601 duration format)
          type: string
          format: date
          example: '2010-07-10'
        onsetType:
          description: Onset type. Value from HPO Onset ontology (HP:0003674), e.g. “congenital onset” (HP:0003577), “adult onset” (HP:0003581).
          type: string
          example: "HP:0003674"
        ageOfOnset:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
        levelSeverity:
          $ref: '#/components/schemas/LevelSeverity'
    Measures:
      description: Measures(s) been taken from Individual, defined by measure ID, date and/or age at measure ment, unit and value.
      type: object
      properties:
        measureId:
          description: Measure ID. Value from Clinical Measurement ontology (CMO).
          type: string
        modifier:
          description: Modifier of the measurement. Value from TBD.
          type: string
        date:
          description: Date of intervention.
          type: string
          format: date
        ageAtMeasure:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
    Exposures:
      description: |
        Exposures(s) occurred to or practiced (lifestyle, behavioural exposures) by Individual,
        defined by exposureID, date and age of onset, dose, schedule and duration.
      type: object
      properties:
        exposureID:
          description: Exposure ID. Value from Environment Exposure Ontology.
          type: string
        modifier:
          description: Modifier of the exposure. Value from TBD.
          type: string
        date:
          description: Date of the exposure.
          type: string
          format: date
        ageAtExposure:
          $ref: 'https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/master/common.yaml#/components/schemas/Age'
    Individual:
      description: |
        #TBD
      type: object
      properties:
        individualId:
          description: |
            Individual identifier (external accession or internal ID).
          type: string
          example: P0001
        datasetId:
          description: Reference to dataset ID.
          type: string
        taxonId:
          description: |
            Taxon ID of Individual.
          type: string
          example: '9606'
        sex:
          description: |
            Sex of the individual.
            Value from NCIT General Qualifier (NCIT:C27993) ontology: UNKNOWN 
            (not assessed or not available) (NCIT:C17998), FEMALE (NCIT:C46113), 
            MALE, (NCIT:C46112) or OTHER SEX (NCIT:C45908).
          type: string
          enum: 
            - NCIT:C17998
            - NCIT:C46113
            - NCIT:C46112
            - NCIT:C45908
          example: 'NCIT:C17998'
        ethnicity:
          description: |
            Ethnic background of the individual. Value from NCIT Race ontology 
            (NCIT:C17049), e.g. NCIT:C126531 (Latin American).
          type: string
          example: 'NCIT:C126531'
        geographicOrigin:
          description: |
            Individual's country or region of origin (birthplace or residence 
            place regardless of ethnic origin). Value from GAZ Geographic 
            Location ontology (GAZ:00000448), e.g. GAZ:00002459 (United States 
            of America).
          type: string
          example: 'GAZ:00002459'
        diseases:
          description: |
            List of disease(s) been diagnosed to the individual, defined by 
            disease ICD10 code, optionally other disease ontology ID(s), age of 
            onset, stage and the presence of family history.
          type: array
          items:
            $ref: '#/components/schemas/Disease'
        pedigrees:
          type: array
          items:
            $ref: '#/components/schemas/Pedigree'
        phenotypicFeatures:
          type: array
          items:
            $ref: '#/components/schemas/PhenotypicFeatures'
        treatments:
          type: array
          items:
            $ref: '#/components/schemas/Treatments'
        interventions:
          type: array
          items:
            $ref: '#/components/schemas/Interventions'
        measures:
          type: array
          items:
            $ref: '#/components/schemas/Measures'
        exposures:
          type: array
          items:
            $ref: '#/components/schemas/Exposures'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3