openapi: 3.0.2
servers: []
info:
  version: "0.1"
  title: GA4GH Beacon Variant Annotation Default Schema
  description: >-
    Schema for variant annotations to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    'Beacon Project'
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    ClinicalRelevance:
      description: |
        Descriptor of clinical relevance as described to the variant, including 
        the variant classification, the disease identifier and references of 
        studies supporting the association.
      type: object
      properties:
        variantClassification:
          description: |
            Value describing the effect of the variant on the disease.
          type: string
          enum:
            - benign
            - likely benign
            - pathogenic
            - likely pathogenic
            - unknown
          example: pathogenic
        diseaseId:
          description: |
            Reference to DiseaseId from Disease object from Individual schema, 
            e.g. MONDO:0003582 (Hereditary breast ovarian cancer syndrome).
          type: string
          example: 'MONDO:0003582'
        references:
          description: |
            List of PUBMED ID(s) of studie(s) describing the variant-disease 
            association.
          type: array
          items:
            type: string
          example: 
            - 'PMC3623669'
            - 'PMID:27153395'
    genomicFeatures:
      description: |
        List of genomic feature(s) affected by the variant
      type: object
      properties:
        class:
          description: |
            Class of genomic region affected by the variant
          type: string
          enum:
            - gene 
            - protein coding transcript 
            - untranslated region 
            - non-coding transcript
          example: "gene"
        featureID:
          description: |
            ID /accession/name of genomic region affected by the variant, matching class in `class`
          type: string
          example:
            - 'TP53'
            - 'GeneID:43740578'
    VariantAnnotations:
      description: |
        Todo
      type: object
      properties:
        variantId:
          description: |
            ID referencing the variant in beacon (internal ID)
          type: string
        genomicHGVSId:
          description: |
            HGVSId descriptor at genomic level, referred to genome assembly 
            defined in Variant Identification.
          type: string
          example: 'NC_000011.9:g.134086816T>C'
        proteinHGVSIds:
          description: |
            List of HGVSId descriptor(s) at protein level (for protein-altering 
            variants).
          type: array
          items:
            type: string
          example: 
            - 'NP_009225.1:p.Glu1817Ter'
            - 'LRG 199p1:p.Val25Gly (preferred)'
        molecularConsequence:
          description: |
            List of Predicted effect at protein level for protein affecting variants
          type: array
          items:
            type: string
          example: 
            - 'nonsense'
            - 'missense'
        geneIds:
          description: |
            List of HGNC ID(s) for gene(s) affected by the variant.
          type: array
          items:
            type: string
          example: 
            - 'HGNC:8157'
        transcriptHGVSId:
          description: |
            List of HGVSId descriptor(s) at transcript level.
          type: array
          items:
            type: string
          example: 
            - 'NC 000023.10(NM004006.2):c.357+1G'
        variantGeneRelationship:
          description: |
            Categorical value classifying the variant according to the broadness 
            of the variant effect in terms of genes: intergenic, 5UTR, 3UTR, 
            single-gene (exonic, intronic), in overlapping genes (exonic, 
            intronic), spanning multiple genes, multiple genes
          type: string
          example: 'single gene'
        clinicalRelevance:
          type: array
          items:
            $ref: '#/components/schemas/ClinicalRelevance'
        variantAlternativeId:
          description: |
            List of cross-referencing ID(s) (CURIE(s)) for the variant 
            in the original databases or variant-level (aggregated) databases for 
            previously described variants (e.g. clinVarId, ClinGen, COSMIC),
          type: array
          items:
            type: string
          example: 
            - 'rs80356868'
            - 'CA003602'
            - 'VCV000055583.1'
        genomicFeatures:
          type: array
          items: 
            $ref: '#/components/schemas/ClinicalRelevance'
        annotationToolVersion:
          description: |
            Tool used for annotation and prediction of variant effects 
          type: string
          example: 'SnpEffVersion=4.3t (build 2017-11-24 1018)'
        molecularEffect:
          description: |
            List of predicted effect at nucleotide level
          type: array
          items:
            type: string
          example:
            - 'STOP_GAINED'
        aminoacidChange:
          description: |
            Lisf of change(s) at aminoacid level for protein affecting variants 
          type: array
          items:
            type: string
          example:
            - 'V304*'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue