openapi: 3.0.2
servers: []
info:
  version: "draft.3.1"
  title: GA4GH Beacon Analysis Default Schema
  description: >-
    Schema for analyses to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    Analysis:
      description: |
        Todo
      type: object
      required:
        - analysisId
      properties:
        analysisId:
          description: |
            Analysis reference ID (external accession or internal ID).
          type: string
        runId:
          description: |
            Run identifier (external accession or internal ID).
          type: string
          example: 'SRR10903401'
        analysisDate:
          description: |
            Date at which analysis was performed, in the ISO8601 date format.
          type: string
          format: date
          example: '2020-01-10'
        pipelineName:
          description: |
            Analysis pipeline and version if a standardized pipeline was used.
          type: string
          example: 'Isaac Whole Genome Sequencing; version 3.0.0.0'
        pipelineRef:
          description: |
            Link to Analysis pipeline resource.
          type: string
        aligner:
          description: |
            Mapping/Alignment software.
          type: string
          example: 'bwa-0.7.8'
        variantCaller:
          description: |
            Variant calling software/pipeline.
          type: string
          example: 'GATK4.0'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3