openapi: 3.0.2
servers: []
info:
  version: "draft.3.1"
  title: GA4GH Beacon Biosample Default Schema
  description: >-
    Schema for biosamples to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    CancerFeature:
      description: |
        Values specifying cancer-specific features, including progression and 
        tumor grade.
      type: object
      properties:
        tumorProgression:
          allOf:
            - description: |
                Descriptor of tumor progres- sion. Value from Neoplasm by 
                Special Category ontology (NCIT:C7062). Tumor progression 
                category indicating primary, metastatic or recurrent progression 
                e.g."Primary Malignant Neoplasm" (NCIT:C84509).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'NCIT:C84509'
                label: 'Primary Malignant Neoplasm'
        tumorGrade:
          allOf:
            - description: |
                Tumor grading. Value from Tumor Grading Characteristic ontology 
                (Mondo Disease Ontology MONDO:0024488), e.g. “Grade 3” 
                (MONDO:0024493)
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'MONDO:0024492'
                label: Grade 3
    Biosample:
      description: |
        TBD
      type: object
      required:
        - biosampleId
      properties:
        biosampleId:
          description: |
            Biosample reference ID (external accession or internal ID).
          type: string
          example: 'S0001'
        individualId:
          description: |
            Reference to individual ID.
          type: string
          example: 'P0001'
        description:
          description: |
            Any relevant info about the biosample that does not fit into any 
            other field in the schema.
          type: string
          example: 'Some free text'
        biosampleStatus:
          allOf:
            - description: |
                Classification of biosample based on their role in study. Value 
                from Experimental Factor Ontology (EFO) Material Sample ontology 
                (OBI:0000747) Classification of the sample in "abnormal sample"
                (EFO:0009655) or "reference sample" (EFO:0009654).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'EFO:0009655'
                label: abnormal sample
        collectionDate:
          description: |
            Date of biosample collection in the ISO8601 date format.
          type: string
          format: date
          example: '2017-07-23'
        individualAgeAtCollection:
          description: |
            Individual's age at the time of sample collection 
            in the ISO8601 duration format `P[n]Y[n]M[n]DT[n]H[n]M[n]S`.
          type: string
          example: 'P32Y6M1D'
        sampleOriginDescriptor:
          description: |
            List of descriptors of origin of biosample.
          type: object
          properties:
            sampleOriginType:
              allOf:
                - description: |
                    Category of sample origin. Value from Ontology for 
                    Biomedical Investigations (OBI) material entity 
                    (BFO:0000040) ontology, e.g. "specimen from organism" 
                    (OBI:0001479), "xenograft" (OBI:0100058), "cell culture" 
                    (OBI:0001876), "cell specimen" (OBI:0001468), "environmental 
                    swab specimen" (OBI:0002613).
                - $ref: 'common.yaml#/components/schemas/OntologyTerm'
                - example:
                    id: 'OBI:0001479'
                    label: 'specimen from organism'
            sampleOriginDetail:
              allOf:
                - description: |
                    Specific instance of sample origin matching the category set 
                    in sampleOriginType. Value from Uber-anatomy ontology (UBERON) 
                    or BRENDA tissue / enzyme source (BTO), Ontology for 
                    Biomedical Investigations (OBI) or Cell Line Ontology (CLO), 
                    e.g. "cerebellar vermis" (UBERON:0004720), "HEK-293T cell" 
                    (BTO:0002181), "nasopharyngeal swab specimen" (OBI:0002606), 
                    "cerebrospinal fluid specimen" (OBI:0002502).
                - $ref: 'common.yaml#/components/schemas/OntologyTerm'
                - example:
                    id: 'UBERON:0004720'
                    label: 'cerebellar vermis'
        obtentionProcedure:
          allOf:
            - description: |
                Ontology value from NCIT Intervention or Procedure ontology 
                describing the procedure for sample obtention, e.g. NCIT:C15189 
                (biopsy).
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example: 
                id: 'NCIT:C15189'
                label: 'biopsy'
        cancerFeatures:
          $ref: '#/components/schemas/CancerFeature'
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3