openapi: 3.0.2
servers: []
info:
  version: "draft.3"
  title: GA4GH Beacon Variant Identification Default Schema
  description: >-
    Schema for variant identifications to be used as default by the Beacon.
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: |
    Beacon Project
  url: 'http://beacon-project.io/'
paths: {}
components:
  schemas:
    VariantIdentification:
      description: |
        Todo
      type: object
      required: 
        - 'variantId'
      properties:
        variantId:
          description: |
            Reference to variant ID (internal ID).
          type: string
        assemblyId:
          description: |
            Genomic assembly accession and version as RefSqeq assembly accession (e.g. "GCG 000001405.39")
            or a versioned assembly name or synonym such as UCSC Genome Browser assembly (e.g. "hg38") or
            Genome Reference consortium Human (e.g. "GRCh38.p13") names.
          type: string
          example: 
            - 'GCG 000001405.39'
            - 'hg38'
            - 'GRCh38.p13'
        refseqId:
          description: |
            Reference sequence Refseq ID and version for genomic reference sequence in which
            variant coordinates are given, e.g. "NC 000009" for human chromosome 9.
            Alternatively, names, synonymous or aliases e.g. "Chr9" when
            assemblyId is given. For organisms with a single reference sequence covering the genome,
            the versioned Refseq ID can be given here as an alternative to the assembly ID and
            version in assemblyId, e.g. "NC 045512.2" for SARS-CoV2 full-length genome reference sequence.
          type: string
          example: 
            - 'NC 000009'
            - 'Chr9'
            - 'NC 045512.2'
        start:
          description: |
            Start position of variant.
          type: integer
          format: int64
          minimum: 0
        end:
          description: |
            End position of variant.
          type: integer
          format: int64
          minimum: 0
        ref:
          description: |
            Reference sequence in start-end coordinates.
          type: string
          pattern: '^([ACGTN]+)$'
        alt:
          description: |
            Alternative sequence in start-end coordinates.
          type: string
          pattern: '^([ACGTN]+)$'
        variantType:
          description: |
            (ontology term object) Type of variant. Value from Sequence Ontology
            e.g. "SNV" (SO:0001483), "structural variant" (SO:0001537).
          type: string
          example: SO:0001483
        info:
          description: |
            Additional unspecified metadata about the dataset response or its 
            content.
          type: object
          example:
            additionalInfoKey1: 
              - additionalInfoValue1
              - additionalInfoValue2
            additionalInfoKey2: additionalInfoValue3
